export const FETCH_DEFINITION_REQUESTED = 'FETCH_DEFINITION_REQUESTED';
export const FETCH_DEFINITION_SUCCEEDED = 'FETCH_DEFINITION_SUCCEEDED';
export const FETCH_DEFINITION_FAILED = 'FETCH_DEFINITION_FAILED';